### ISSUE TITLE
Dev without API Server

### ISSUE THREAD

**Issue by bt** [auronvila/mantine-template#1]
Hi @auronvila,

Thank you for putting together this boilerplate. I'm starting a new project and I decided to use your boilerplate to kickstart the process.

I just wanted to see, do you have any tools in which it would allow for development without an API server? At the current time, I can see that things are expecting a real response from an API server.

Would be good to see how we should approach this; then I can separate the development between frontend and backend teams.

**Comment by auronvila** [comment]
Hi @bt,

Thank you for choosing this template. This issue can be solved by using a mockApiService. I wanted to get this template ready as soon as possible so I did not implement it but I can start working on a mock service for authentication and this implementation would solve your issue.

**Comment by bt** [comment]
> Hi @bt,
> 
> Thank you for choosing this template. This issue can be solved by using a mockApiService. I wanted to get this template ready as soon as possible so I did not implement it but I can start working on a mock service for authentication and this implementation would solve your issue.

That would be amazing, thank you!

**Comment by auronvila** [comment]
I got this issue and I am starting to implement it. Thank you again for your feedback if you have any other ideas please open new issues.

Happy coding!!

**Comment by auronvila** [comment]
Hey I added the mock api service. You can start using it. The user credentials are provided in sign in form by default. You can disable the mock api by setting the enable mock to false in appConfig. Later I will update the docs and include the details about fake api. For now you can start using it freely.
